### ISSUE TITLE
 colcon build fails on Focal 20.04 ROS2 Foxy 

### ISSUE THREAD

**Issue by mis-eu** [lgsvl/ros2-lgsvl-bridge#4]
### steps to reproduce on Ubuntu 20.04 with ROS Foxy
Note: all dependencies have been installed. 

`$ git clone https://github.com/lgsvl/ros2-lgsvl-bridge.git`
`sudo apt install libboost-all-dev`
`source /opt/ros/foxy/setup.bash`
`colcon build --cmake-args '-DCMAKE_BUILD_TYPE=Release'

 ---  
Starting >>> lgsvl_bridge
--- stderr: lgsvl_bridge
In file included from /home/esofi/ros2-lgsvl-bridge/src/types.cc:8:
/home/esofi/ros2-lgsvl-bridge/src/types.h:15:10: fatal error: rosidl_generator_c/message_type_support_struct.h: No such file or directory
   15 | #include <rosidl_generator_c/message_type_support_struct.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/esofi/ros2-lgsvl-bridge/src/node.h:10,
                 from /home/esofi/ros2-lgsvl-bridge/src/node.cc:8:
/home/esofi/ros2-lgsvl-bridge/src/types.h:15:10: fatal error: rosidl_generator_c/message_type_support_struct.h: No such file or directory
   15 | #include <rosidl_generator_c/message_type_support_struct.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
make[2]: *** [CMakeFiles/lgsvl_bridge.dir/build.make:128: CMakeFiles/lgsvl_bridge.dir/src/types.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/lgsvl_bridge.dir/build.make:102: CMakeFiles/lgsvl_bridge.dir/src/node.cc.o] Error 1
In file included from /home/esofi/ros2-lgsvl-bridge/src/node.h:10,
                 from /home/esofi/ros2-lgsvl-bridge/src/bridge.cc:9:
/home/esofi/ros2-lgsvl-bridge/src/types.h:15:10: fatal error: rosidl_generator_c/message_type_support_struct.h: No such file or directory
   15 | #include <rosidl_generator_c/message_type_support_struct.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lgsvl_bridge.dir/build.make:63: CMakeFiles/lgsvl_bridge.dir/src/bridge.cc.o] Error 1
In file included from /home/esofi/ros2-lgsvl-bridge/src/node.h:10,
                 from /home/esofi/ros2-lgsvl-bridge/src/client.cc:10:
/home/esofi/ros2-lgsvl-bridge/src/types.h:15:10: fatal error: rosidl_generator_c/message_type_support_struct.h: No such file or directory
   15 | #include <rosidl_generator_c/message_type_support_struct.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lgsvl_bridge.dir/build.make:76: CMakeFiles/lgsvl_bridge.dir/src/client.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/lgsvl_bridge.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< lgsvl_bridge [10.6s, exited with code 2]

Summary: 0 packages finished [10.8s]
  1 package failed: lgsvl_bridge
  1 package had stderr output: lgsvl_bridge

**Comment by hadiTab** [comment]
You need to use the `foxy-devel` branch for Foxy.

**Comment by hadiTab** [comment]
Closing. Feel free to reopen if you are still having issues.
