### ISSUE TITLE
ros2-lgsvl-bridge does not build

### ISSUE THREAD

**Issue by dmlachap** [lgsvl/ros2-lgsvl-bridge#6]
I'm using ROS2 "Foxy" (but I also have ROS1 "Noetic" on my machine) on Ubuntu 20.04, and building ros2-lgsvl-bridge with colcon, when I get a series of build errors resembling the following:
`In file included from /home/dan/ros2-lgsvl-bridge/src/node.h:10,
                 from /home/dan/ros2-lgsvl-bridge/src/node.cc:8:
/home/dan/ros2-lgsvl-bridge/src/types.h:15:10: fatal error: rosidl_generator_c/message_type_support_struct.h: No such file or directory
   15 | #include <rosidl_generator_c/message_type_support_struct.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

A file named `message_type_support_struct.h` *does* exist - but in the `/opt/ros/foxy/include/rosidl_runtime_c` directory. How can I resolve this?

**Comment by hadiTab** [comment]
@dmlachap thanks for your interest in the simulator. The master branch does not compile with Foxy. For Foxy please use the `foxy-devel` branch.

**Comment by dmlachap** [comment]
Thanks, that resolved it.
